services:
  web:
    environment:
      - ENV_TYPE=production
    platform: linux/amd64
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"

  localweb:
    environment:
      - ENV_TYPE=development
    platform: linux/arm64
    stdin_open: true
    tty: true
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.3
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    command: --mysql-native-password=ON --skip-ssl=ON --disable-log-bin

  tests:
    build:
      context: .
      args:
        MODE: dev
    platform: linux/arm64
    security_opt:
      - seccomp:unconfined  # for strace
    environment:
      - ENV_TYPE=development.unittest
    volumes:
      - ./.bash_history:/root/.bash_history
      - ./:/workdir

    command: >
      bash -c "
      cd /workdir/ && flake8 &&
      cd /workdir/wallet_api/ && py.test"
    depends_on:
      - db

volumes:
  mysql_data: