# Generated by Django 5.1.5 on 2025-01-24 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=18, max_digits=37)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_gtzero')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=18, max_digits=37)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='apicore.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'indexes': [models.Index(fields=['wallet'], name='apicore_tra_wallet__f263b4_idx'), models.Index(fields=['wallet', 'amount'], name='apicore_tra_wallet__5ea1a8_idx'), models.Index(fields=['amount'], name='apicore_tra_amount_259952_idx'), models.Index(fields=['txid'], name='apicore_tra_txid_bad75c_idx')],
            },
        ),
    ]
