# Generated by Django 5.1.5 on 2025-01-24 22:01

from django.db import migrations
from django.db.migrations import RunSQL

trigger = '''
CREATE TRIGGER update_balance
AFTER INSERT ON apicore_transaction
FOR EACH ROW
BEGIN
    UPDATE apicore_wallet
    SET balance = (
        SELECT COALESCE(SUM(amount), 0)
        FROM apicore_transaction
        WHERE apicore_transaction.wallet_id = NEW.wallet_id
    )
    WHERE id = NEW.wallet_id;
END;
'''


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0001_initial'),
    ]

    operations = [
        RunSQL(trigger)
    ]
